name: tanymtest_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  provider:
  cloud_firestore: ^4.15.4
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  equatable: ^2.0.5
#  bloc: ^8.1.3
#  flutter_bloc: ^8.1.4
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.6
  image_picker: ^1.1.0
  firebase_storage: ^11.7.2
  table_calendar: ^3.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
        - asset: assets/fonts/nunito_medium.ttf
        - asset: assets/fonts/nunito_semibold.ttf
        - asset: assets/fonts/nunito_bold.ttf
